version: '3'
services:
  air-static:
    build: .
    restart: always
    ports:
      - '80:80'
    depends_on:
      - air-api
  air-api:
    build: https://github.com/gretzkiy/air-schedule-api-server.git
    restart: always
